apiVersion: apps/v1
kind: Deployment
metadata:
  name: zk2etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zk2etcd
  template:
    metadata:
      labels:
        app: zk2etcd
    spec:
      containers:
      - name: zk2etcd
        image: imroc/zk2etcd:1.3.0
        imagePullPolicy: Always
        command: [ "/bin/zk2etcd" ]
        args:
        - sync
        - --zookeeper-servers=zookeeper:2181
        - --zookeeper-prefix=/dubbo
        - --zookeeper-exclude-prefix=/dubbo/config
        - --etcd-servers=etcd:2379
        - --log-level=debug
        - --concurrent=50
        - --fullsync-interval=5m
        - --etcd-cacert=/certs/ca.crt
        - --etcd-cert=/certs/cert.pem
        - --etcd-key=/certs/key.pem
        - --enable-event-log
        - --redis-server=redis:6379
        - --redis-password=hello:world

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: zk2etcd

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zk2etcd
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zk2etcd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: zk2etcd
subjects:
- kind: ServiceAccount
  name: zk2etcd