apiVersion: apps/v1
kind: Deployment
metadata:
  name: zk2etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zk2etcd
  template:
    metadata:
      labels:
        app: zk2etcd
    spec:
      containers:
      - name: zk2etcd
        image: imroc/zk2etcd:0.5.0
        imagePullPolicy: Always
        command: [ "/bin/zk2etcd" ]
        args:
        - --zookeeper-servers=zookeeper:2181
        - --zookeeper-prefix=/dubbo
        - --etcd-servers=etcd:2379
        - --log-level=debug
